services:
  - type: web
    name: my-django-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn Tutorial.wsgi:application
    envVars:
      - key: DB_ENGINE
        value: django.db.backends.postgresql
      - key: DB_NAME
        fromDatabase:
          name: my-django-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: my-django-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: my-django-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: my-django-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: my-django-db
          property: port
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false

databases:
  - name: my-django-db
