# Generated by Django 5.1.7 on 2025-08-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatas',
            name='isApproved',
            field=models.BooleanField(default=True),
        ),
    ]
